version: '3'
services:
  php:
    image: php:8.1-fpm
    volumes:
      - ./sensvinylo-musique:/sensvinylo-musique
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: ${PHPMYADMIN_NAME}
      PMA_USER: ${PHPMYADMIN_USER}
      PMA_PASSWORD: ${PHPMYADMIN_PASSWORD}
    ports:
      - "8082:80"
    depends_on:
      - db
volumes:
  dbdata:
