version: '3'
services:
  php:
    image: php:8.1-fpm
    volumes:
      - ./sensvinylo-musique:/sensvinylo-musique
    depends_on:
      - db
    mem_limit: 512M
    cpus: '0.5'

  db:
    image: mysql:8.0
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always
    volumes:
      - ./dbdata:/var/lib/mysql
    command: --max-allowed-packet=64M --wait-timeout=28800 --interactive-timeout=28800
    ports:
      - "3307:3306"
    mem_limit: 1G
    cpus: '1.0'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: ${PMA_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8082:80"
    depends_on:
      - db
    mem_limit: 256M
    cpus: '0.25'

volumes:
  dbdata:
