version: '3'
services:
  php:
    image: php:8.1-fpm
    volumes:
      - ./sensvinylo-musique:/sensvinylo-musique
    depends_on:
      - db
  db:
    image: mysql:8.0
    env_file:
      - .env.local
    volumes:
      - ./dbdata:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env.local
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - db
volumes:
  dbdata:
